name: upwork_tyler
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  dartz:
  dartx:
  equatable:
  flutter_bloc:
  flutter_screenutil:
  permission_handler:
  http:
  url_launcher:
  #firebase_core:
  #firebase_analytics:
  #path_provider:
  #shared_preferences:
  #sqflite:
  #firebase_admob:  
  #path_provider: 
  #uuid: 
  #shared_preferences: 
  #flutter_swiper:
  #auto_size_text:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart:


flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg